run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gci
    - goconst
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goconst:
    min-occurrences: 5
  goimports:
    local-prefixes: github.com/Lew-Lew/plop
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/Lew-Lew/plop)
