openapi: 3.0.1
info:
  title: PLOP API
  version: 1.0.0

paths:
  /word:
    get:
      summary: Get the 10 letters of the day
      operationId: wordGet
      tags: [plop]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  format: string
    post:
      summary: Verify if a word is valid
      operationId: wordVerify
      tags: [plop]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                word:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  exist:
                    type: boolean
